package com.belyabl9.api;

public enum RequestType {
	SEND_TEXT_MESSAGE,
	SEND_MEDIA_MESSAGE,
	GET_ALL_USERS,
	UPDATE_USER_INFO,
	GET_UNSENT_MESSAGES,
	GET_UPDATES,
	AUTH, 
	GET_USER,
	MARK_MESSAGES_AS_READ,
	CONVERSATION_HISTORY,
	GET_MEDIA_MESSAGES,
	REMOVE_MEDIA_MESSAGE,
	GET_DEPARTMENTS,
	CREATE_NEW_USER,
	CREATE_NEW_DEPARTMENT,
	;
}