package model.server;

public enum RequestTypes {
	TEXT_MESSAGE, MEDIA_MESSAGE, ALL_USERS, UPDATE_USER_INFO, SEND_FILE, UNSENT_MESSAGES, AUTH, 
	GET_USER, MARK_AS_READ_MESSAGES, CONVERSATION_HISTORY, MEDIA_MESSAGES, REMOVE_MEDIA_MESSAGE,
	DEPARTMENTS, NEW_USER, NEW_DEPARTMENT
}
